project:
  type: website

website:
  title: "Lake Rotoehu Data Product"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "QA/QC"
        href: rotoehu-qc.qmd
      - text: "Data"
        href: rotoehu-qc-summary.qmd
      - text: "Metadata"
        href: metadata.qmd
      - text: "About"
        href: index.qmd

format:
  html:
    theme: cosmo
    toc: true
